name: Build React Redux Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List Repository Contents
        run: ls -R

      - name: Scrap ids
        run: |
          tsc scapper/htmlScrapper.ts
          node scapper/htmlScrapper.js
