name: CI Pipeline

on:
  push: {}

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install modules
        run: npm install

      - name: Build
        run: npm run build